# Generated by Django 5.0.3 on 2024-03-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пациент', 'verbose_name_plural': 'пациенты'},
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telegram'),
        ),
    ]
