# Generated by Django 5.0.3 on 2024-03-15 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'врач',
                'verbose_name_plural': 'врачи',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'специализация',
                'verbose_name_plural': 'специализация',
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('price', models.PositiveIntegerField(verbose_name='стоимость')),
                ('doctor', models.ManyToManyField(related_name='врач', to='diagerda.doctor')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='услуги', to='diagerda.speciality', verbose_name='специализация')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата и время приема')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='записи', to=settings.AUTH_USER_MODEL, verbose_name='пациент')),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='записи', to='diagerda.diagnostic', verbose_name='диагностика')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='записи', to='diagerda.doctor', verbose_name='врач')),
            ],
            options={
                'verbose_name': 'запись на диагностику',
                'verbose_name_plural': 'записи на диагностику',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='врачи', to='diagerda.speciality', verbose_name='специализация'),
        ),
    ]
