# Generated by Django 5.0.3 on 2024-03-14 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagerda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='записи', to=settings.AUTH_USER_MODEL, verbose_name='пациент'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='записи', to='diagerda.diagnostic', verbose_name='диагностика'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='doctor',
            field=models.ManyToManyField(related_name='doctor', to='diagerda.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='записи', to='diagerda.doctor', verbose_name='врач'),
        ),
    ]
