# Generated by Django 5.0.3 on 2024-03-15 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagerda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Врачи', to='diagerda.speciality', verbose_name='Специализация'),
        ),
    ]
