# Generated by Django 5.0.3 on 2024-03-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagerda', '0002_speciality_icon_alter_doctor_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='speciality',
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.ManyToManyField(related_name='Врачи', to='diagerda.speciality', verbose_name='Специализация'),
        ),
    ]
