# Generated by Django 5.0.3 on 2024-03-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagerda', '0003_remove_doctor_speciality_doctor_speciality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'специализация', 'verbose_name_plural': 'специализации'},
        ),
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
