# Generated by Django 5.0.3 on 2024-03-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagerda', '0004_alter_speciality_options_speciality_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='doctors',
            field=models.ManyToManyField(blank=True, null=True, related_name='Специализация', to='diagerda.doctor', verbose_name='Врачи'),
        ),
    ]
