# Generated by Django 5.0.3 on 2024-03-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagerda', '0005_speciality_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.ManyToManyField(related_name='speciality', to='diagerda.speciality', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='doctors',
            field=models.ManyToManyField(blank=True, null=True, related_name='Doctor', to='diagerda.doctor', verbose_name='Врачи'),
        ),
    ]
